import { useMemo,useState } from 'react'; import { ScrollView,StyleSheet,Text,View,Pressable } from 'react-native'; import { router,useLocalSearchParams } from 'expo-router'; import { Ionicons } from '@expo/vector-icons'; import { findSkill } from '../../../data/skills'; import { useStudentProfile } from '../../../context/StudentProfileContext';
function buildGuide(skill,profile){const interest=profile.interests?.trim();const barriers=profile.barriers?.trim();const strengths=profile.strengths?.trim();const base=skill.goals.slice(0,3);return [
 {title:'Get ready',detail:`Show what ${skill.title.toLowerCase()} will look like and keep the first direction short.${interest?` Connect the visual to an interest such as ${interest}.`:''}`},
 {title:'Do one step',detail:`Present one clear step at a time and pair the words with a picture or gesture.${barriers?` Adapt for: ${barriers}.`:''}`},
 {title:'Check and continue',detail:`Pause after each step, acknowledge success, and show what comes next.${strengths?` Build on strengths such as ${strengths}.`:''}`},
 {title:'Finish and celebrate',detail:`Show a clear “finished” cue and reinforce progress toward: ${base.join(', ')}.`},
];}
export default function Visual(){const {skillId}=useLocalSearchParams();const skill=findSkill(skillId);const {profile}=useStudentProfile();const [generated,setGenerated]=useState(false);const guide=useMemo(()=>skill?buildGuide(skill,profile):[],[skill,profile]);if(!skill)return null;const missing=!profile.strengths&&!profile.barriers&&!profile.interests;return <ScrollView style={s.page}><View style={s.header}><Pressable onPress={()=>router.back()}><Ionicons name="chevron-back" size={28}/></Pressable><Text style={s.title}>Step-by-Step Visual</Text><View style={{width:28}}/></View><View style={s.hero}><Ionicons name="sparkles" size={34} color="#7559E8"/><View style={{flex:1}}><Text style={s.heroTitle}>Personalized Step-by-Step Visual</Text><Text style={s.intro}>Uses the student profile and psychologist strategies for {skill.title}.</Text></View></View>{missing&&<Pressable style={s.warning} onPress={()=>router.push('/student-profile')}><Ionicons name="information-circle-outline" size={22} color="#A56A00"/><Text style={s.warningText}>Add strengths, learning barriers, and interests to the Student Profile for better personalization.</Text></Pressable>}<Pressable style={s.button} onPress={()=>setGenerated(true)}><Ionicons name="sparkles" size={20} color="#FFF"/><Text style={s.buttonText}>{generated?'Regenerate Visual':'Generate My Child’s Visual'}</Text></Pressable>{generated&&<View style={s.result}><Text style={s.resultTitle}>{profile.name?`${profile.name}’s `:''}{skill.title}</Text>{guide.map((x,i)=><View key={x.title} style={s.step}><View style={s.stepNum}><Text style={s.stepNumText}>{i+1}</Text></View><View style={{flex:1}}><Text style={s.stepTitle}>{x.title}</Text><Text style={s.stepDetail}>{x.detail}</Text></View></View>)}<Text style={s.disclaimer}>Prototype: this version demonstrates the personalization flow locally. Connect the Generate button to your secure AI backend/Cloud Function before production use.</Text></View>}</ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F2F9FF'},header:{paddingTop:56,paddingHorizontal:20,paddingBottom:18,backgroundColor:'#FFF',flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{fontSize:20,fontWeight:'800'},hero:{margin:18,backgroundColor:'#FFF',borderRadius:20,padding:18,flexDirection:'row',gap:13},heroTitle:{fontSize:18,fontWeight:'800'},intro:{color:'#718096',lineHeight:20,marginTop:5},warning:{marginHorizontal:18,backgroundColor:'#FFF5D9',borderRadius:14,padding:13,flexDirection:'row',gap:9},warningText:{flex:1,color:'#76520E',lineHeight:19},button:{margin:18,backgroundColor:'#258DEB',borderRadius:18,padding:17,flexDirection:'row',justifyContent:'center',gap:9},buttonText:{color:'#FFF',fontSize:16,fontWeight:'800'},result:{marginHorizontal:18,marginBottom:36,backgroundColor:'#FFF',borderRadius:20,padding:18},resultTitle:{fontSize:22,fontWeight:'800',marginBottom:8},step:{flexDirection:'row',gap:12,paddingVertical:13,borderBottomWidth:1,borderBottomColor:'#EEF1F5'},stepNum:{width:38,height:38,borderRadius:19,backgroundColor:'#EEE9FF',alignItems:'center',justifyContent:'center'},stepNumText:{fontWeight:'800',color:'#7055DB'},stepTitle:{fontSize:16,fontWeight:'800'},stepDetail:{fontSize:14,color:'#5F6B7A',lineHeight:20,marginTop:3},disclaimer:{fontSize:12,color:'#8A94A3',lineHeight:17,marginTop:16}});
