import { ScrollView, StyleSheet, Text, TextInput, View, Pressable } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useStudentProfile } from '../context/StudentProfileContext';

const fields=[
 {key:'strengths',label:'Strengths',hint:'What does your child do well?',placeholder:'Example: learns well with pictures, strong memory, enjoys routines'},
 {key:'barriers',label:'Learning Barriers',hint:'What makes learning challenging?',placeholder:'Example: difficulty following multistep directions, sensitivity to sounds/smells, mobility issues'},
 {key:'interests',label:'Interests',hint:'What does your child enjoy?',placeholder:'Example: trains, music, animals, space, favorite characters'},
];
export default function StudentProfile(){const {profile,updateProfile}=useStudentProfile();return <ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.header}><Pressable onPress={()=>router.back()}><Ionicons name="chevron-back" size={28}/></Pressable><Text style={s.headerTitle}>Student Profile</Text><View style={{width:28}}/></View><View style={s.avatar}><Ionicons name="person-outline" size={48} color="#2F8CF0"/></View><Text style={s.section}>Basic Information</Text><TextInput style={s.input} value={profile.name} onChangeText={v=>updateProfile({name:v})} placeholder="Child's first name or nickname"/><TextInput style={s.input} value={profile.age} onChangeText={v=>updateProfile({age:v})} placeholder="Age (optional)" keyboardType="number-pad"/>{fields.map(f=><View key={f.key} style={s.field}><Text style={s.label}>{f.label}</Text><Text style={s.hint}>{f.hint}</Text><TextInput style={s.textarea} multiline value={profile[f.key]} onChangeText={v=>updateProfile({[f.key]:v})} placeholder={f.placeholder} textAlignVertical="top"/></View>)}<View style={s.note}><Ionicons name="shield-checkmark-outline" size={22} color="#438A6A"/><Text style={s.noteText}>This profile is used to personalize strategies and step-by-step visuals for your child.</Text></View><Pressable style={s.button} onPress={()=>router.back()}><Text style={s.buttonText}>Save Profile</Text></Pressable></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F2F9FF'},content:{paddingBottom:40},header:{paddingTop:56,paddingHorizontal:20,paddingBottom:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#FFF'},headerTitle:{fontSize:21,fontWeight:'800'},avatar:{width:92,height:92,borderRadius:46,backgroundColor:'#DDEEFF',alignSelf:'center',alignItems:'center',justifyContent:'center',marginTop:24},section:{fontSize:17,fontWeight:'800',margin:20,marginBottom:10},input:{marginHorizontal:20,marginBottom:12,backgroundColor:'#FFF',borderWidth:1,borderColor:'#D9E4EE',borderRadius:12,padding:14,fontSize:16},field:{marginHorizontal:20,marginTop:14,backgroundColor:'#FFF',borderRadius:18,padding:16},label:{fontSize:17,fontWeight:'800',color:'#17213A'},hint:{fontSize:13,color:'#718096',marginTop:3,marginBottom:10},textarea:{minHeight:92,borderWidth:1,borderColor:'#D9E4EE',borderRadius:12,padding:12,fontSize:15,lineHeight:21},note:{margin:20,flexDirection:'row',gap:10,backgroundColor:'#E9F8F0',padding:14,borderRadius:14},noteText:{flex:1,color:'#426557',lineHeight:19},button:{marginHorizontal:20,backgroundColor:'#258DEB',borderRadius:18,padding:17,alignItems:'center'},buttonText:{color:'#FFF',fontSize:17,fontWeight:'800'}});
